name: ThriveWell Email Workflow

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  send_emails:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create Google service account JSON
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > Zenquotes/crested-pursuit-457714-c8-f5a68d29f980.json

      - name: Run DB insertion/update/verification
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/Zenquotes/crested-pursuit-457714-c8-f5a68d29f980.json
          URL: ${{ secrets.GOOGLE_FORM_URL }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python Zenquotes/db_conn.py

      - name: Run email sending
        env:
          SENDER_EMAIL: ${{ secrets.EMAIL_USER }}
          SENDER_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python Zenquotes/Wellness.py

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: workflow-logs
          path: Zenquotes/logs/
