name: ThriveWell Email Workflow

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  send_emails:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Run DB insertion, update and verification
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          API_KEY: ${{secrets.API_KEY }}
        run: |
          echo "Running db_conn.py============="
          python Zenquotes/db_conn.py
          echo "db_conn.py finished running========="

      - name: Run Email sending
        env:
          SENDER_EMAIL: ${{ secrets.EMAIL_USER }}
          SENDER_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          API_KEY: ${{secrets.API_KEY }}
        run: |
          echo "Running Wellness.py============="
          python Zenquotes/Wellness.py
          echo "Wellness.py finished run========="
